Repository OLXClone-SE/OLXClone, pull requests merged in 2022-04, with the labels that each got.

#156 Front end tests
  workspaces/client/cypress/integration/unit/categoryVerify.spec.js
  workspaces/client/cypress/integration/unit/dropdownEditProfile.spec.js
  workspaces/client/cypress/integration/unit/editProfileNavigation.spec.js
  workspaces/client/cypress/integration/unit/loginNavigation.spec.js
  workspaces/client/cypress/integration/unit/loginValidation.spec.js
  workspaces/client/cypress/integration/unit/signupVerify.spec.js
  workspaces/client/cypress/support/commands.js
  workspaces/client/cypress/support/utils.js
  workspaces/client/src/DetailsComponent/DetailsComponent.tsx
Labels: ui, api, testing, unit tests - FrontEnd, sprint3, frontend

#157 Front end tests
  package.json
  workspaces/client/cypress/integration/unit/signupVerify.spec.js
  workspaces/client/cypress/support/utils.js
  workspaces/client/src/DetailsComponent/DetailsComponent.tsx
  yarn.lock
Labels: ui, sprint3, frontend

#159 Products implementation
  workspaces/client/src/ReduxActions/SellActions.ts
  workspaces/client/src/ReduxSlices/SellSlice.ts
  workspaces/client/src/SellComponent/SellComponent.tsx
  workspaces/client/src/Types/user.ts
  workspaces/client/src/app.constants.ts
Labels: ui, sprint3

#160 Products implementation
  workspaces/client/src/NavBarComponent/NavBarComponent.tsx
  workspaces/client/src/Utils/CategoriesList.ts
Labels: ui, sprint3

#161 product issues fix
  workspaces/client/src/ReduxSlices/ProductSlice.ts
Labels: ui, sprint3

#162 Products implementation
  workspaces/client/src/SellComponent/SellComponent.css
  workspaces/client/src/SellComponent/SellComponent.tsx
  workspaces/client/src/Store/store.ts
Labels: ui, sprint3

#163 Products implementation
  workspaces/client/src/index.tsx
  workspaces/server/controller.go
  workspaces/server/handlers/saveProductHandler.go
  workspaces/server/paths/paths.go
Labels: sprint3, backend

#165 Search functionality
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/ReduxSlices/SearchSlice.ts
  workspaces/client/src/SearchComponent/SearchComponent.tsx
  workspaces/client/src/Store/store.ts
Labels: sprint3, frontend

#166 updated sprint 3 md file
  Sprint3.md
Labels: sprint3

#168 update md file
  Sprint3.md
Labels: sprint3

#169 Api tests
  workspaces/server/handlers/getProductsHandler_test.go
  workspaces/server/handlers/getUserDetailsHandler_test.go
  workspaces/server/handlers/loginHandler_test.go
  workspaces/server/handlers/resetPasswordHandler.go
  workspaces/server/handlers/resetPasswordHandler_test.go
  workspaces/server/handlers/signupHandler_test.go
  workspaces/server/handlers/updateUserDetails_test.go
  workspaces/server/handlers/userVerificationHandler_test.go
  workspaces/server/package.json
  workspaces/server/utilities/apiTestUtilities.go
  workspaces/server/utilities/dbUtilities_test.go
  workspaces/server/utilities/mailUtility_test.go
Labels: api, backend unit test, sprint3, backend

#170 OLXClone-133: update sprint3.md file
  Sprint3.md
Labels: documentation, sprint3, backend

#171 Sprint4 documentation
  Sprint4.md
Labels: documentation, sprint4

#174 Api documentation
  APIDocumentation.md
Labels: documentation, api

#175 Jwt impl
  workspaces/client/src/axiosInstance.ts
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/handlers/getProductsHandler.go
  workspaces/server/handlers/getUserDetails.go
  workspaces/server/handlers/loginHandler.go
  workspaces/server/handlers/saveProductHandler.go
  workspaces/server/handlers/signupHandler.go
  workspaces/server/handlers/updateUserDetails.go
  workspaces/server/main.go
  workspaces/server/utilities/verifyCookie.go
Labels: documentation, api

#176 Products implementation
  package.json
  workspaces/client/src/CardComponent/CardComponent.tsx
  workspaces/client/src/DetailsComponent/DetailsComponent.tsx
  workspaces/client/src/ForgotPasswordComponent/ForgotPasswordComponent.tsx
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/NavBarComponent/NavBarComponent.tsx
  workspaces/client/src/ProfileComponent/ProfileComponent.tsx
  workspaces/client/src/SellComponent/SellComponent.tsx
  workspaces/client/src/index.tsx
  yarn.lock
Labels: ui, frontend

#182 sprint 4 documentation
  Sprint4.md
Labels: documentation, sprint4

#185 Products implementation
  Sprint4.md
Labels: documentation, sprint4

#183 Image upload
  workspaces/client/src/ReduxActions/UploadImageActions.ts
  workspaces/client/src/ReduxSlices/UploadImageSlice.ts
  workspaces/client/src/SellComponent/SellComponent.css
  workspaces/client/src/SellComponent/SellComponent.tsx
  workspaces/client/src/Store/store.ts
  workspaces/client/src/Types/ImageUploadTypes.ts
  workspaces/client/src/app.constants.ts
Labels: enhancement, olxclone, frontend, sprint4

#184 Image api
  workspaces/server/controller.go
  workspaces/server/handlers/getImagesHandler.go
  workspaces/server/paths/paths.go
Labels: api, backend, sprint4

#186 Products implementation
  Sprint4.md
Labels: documentation, sprint4

#188 updated session time out to 30 mins
  workspaces/server/handlers/loginHandler.go
Labels: api, backend, sessions

#187 sprint 4 doc updates-5
  Sprint4.md
Labels: documentation, sprint4

#191 Front end test cases
  workspaces/client/cypress/integration/unit/sellProductNavigation.spec.js
  workspaces/client/cypress/support/utils.js
Labels: ui, testing, sprint4

#192 Add backend unit test video
  Sprint4.md
Labels: backend unit test, sprint4

#195 Front end test cases
  workspaces/client/cypress/fixtures/sample.jpg
  workspaces/client/cypress/integration/unit/verifyLogout.spec.js
  workspaces/client/cypress/integration/unit/verifyUploadImageService.spec.js
Labels: olxclone, ui, testing, frontend, sprint4

#199 Products implementation
  Sprint4.md
Labels: documentation, sprint4
