Repository OLXClone-SE/OLXClone, pull requests merged in 2022-03, with the labels that each got.

#89 Signup Redirection
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
Labels: ui, sprint2

#90 Update user details api
  workspaces/server/constants/dbconstants.go
  workspaces/server/controller.go
  workspaces/server/handlers/updateUserDetails.go
  workspaces/server/models/usermodels.go
  workspaces/server/paths/paths.go
Labels: api, sprint2

#92 Password hash
  workspaces/server/handlers/loginHandler.go
  workspaces/server/handlers/signupHandler.go
  workspaces/server/utilities/hashingUtilities.go
Labels: api, sprint2

#95 Homepage Redirection
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/index.tsx
Labels: ui, sprint2

#87 Connected user login to backend API
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/ReduxActions/LoginActions.ts
  workspaces/client/src/ReduxSlices/LoginSlice.ts
Labels: api, sprint2

#97 Navigationbar
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/NavBarComponent/NavBarComponent.tsx
Labels: ui, sprint2

#99 Homepage Initialization
  workspaces/client/package.json
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  yarn.lock
Labels: ui, sprint2

#100 Search bar Implementation
  package.json
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/SearchComponent/SearchComponent.css
  workspaces/client/src/SearchComponent/SearchComponent.tsx
Labels: ui, sprint2

#102 HomePage Search bar
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
Labels: ui, sprint2

#103 Package Updates for Bootstrap
  package.json
  workspaces/client/package.json
  yarn.lock
Labels: ui, sprint2

#104 Home Page nav bar bug fix
  workspaces/client/src/index.tsx
Labels: ui, sprint2

#105 Cardcomponent
  workspaces/client/src/CardComponent/CardComponent.css
  workspaces/client/src/CardComponent/CardComponent.tsx
Labels: olxclone, ui, sprint2

#108 added mockgen
  workspaces/server/go.mod
  workspaces/server/go.sum
Labels: olxclone, api, sprint2, uni tests

#109 Login form
  package.json
  workspaces/client/package.json
  workspaces/client/public/index.html
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/SearchComponent/SearchComponent.tsx
  workspaces/client/src/images/product.jpg
  yarn.lock
Labels: ui, sprint2

#111 OLXCLONE : Cypress initial setup for Testing
  package.json
  workspaces/client/cypress.json
  workspaces/client/cypress/fixtures/example.json
  workspaces/client/cypress/plugins/index.js
  workspaces/client/cypress/support/commands.js
  workspaces/client/cypress/support/index.js
  workspaces/client/package.json
  yarn.lock
Labels: sprint2, testing

#113 Profile Page Implementation
  workspaces/client/src/CardComponent/CardComponent.tsx
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/ProfileComponent/ProfileComponent.tsx
  workspaces/client/src/images/profile.png
  workspaces/client/src/index.tsx
Labels: ui, sprint2

#115 Front end tests
  workspaces/client/cypress/integration/unit/signup.spec.js
  workspaces/client/cypress/integration/unit/signupVerify.spec.js
Labels: ui, sprint2, unit tests - FrontEnd

#116 cypress eslint issue fix
  package.json
  workspaces/client/cypress/.eslintrc.json
  workspaces/client/package.json
  yarn.lock
Labels: ui, sprint2, unit tests - FrontEnd

#118 OLXClone-117: add unit test to check navigation to sign up page on clicking link in login page
  workspaces/client/cypress/integration/unit/navigateSignup.spec.js
  workspaces/server/go.mod
Labels: ui, sprint2, testing

#120 OLXClone-119: add commands to use cypress
  package.json
  workspaces/client/package.json
Labels: sprint2, testing, unit tests - FrontEnd

#121 add test case to test db connection with server
  workspaces/server/utilities/dbUtilities_test.go
Labels: sprint2, backend unit test, testing

#122 Server tests
  workspaces/server/utilities/dbUtilities.go
  workspaces/server/utilities/dbUtilities_test.go
  workspaces/server/utilities/hashingUtilities_test.go
  workspaces/server/utilities/jsonUtilities_test.go
  workspaces/server/utilities/mailUtility.go
  workspaces/server/utilities/mailUtility_test.go
  workspaces/server/utilities/otpUtilities_test.go
Labels: sprint2, backend unit test

#123 sanitized code
  workspaces/client/src/App.tsx
  workspaces/client/src/ForgotPasswordComponent/ForgotPasswordComponent.tsx
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
Labels: sprint2

#124 Front end tests
  package.json
  workspaces/client/cypress/integration/unit/categoryVerify.spec.js
  workspaces/client/package.json
  yarn.lock
Labels: ui, sprint2, unit tests - FrontEnd

#125 UI tests
  workspaces/client/cypress/integration/unit/dropdownEditProfile.spec.js
  workspaces/client/cypress/integration/unit/editProfileNavigation.spec.js
Labels: sprint2, unit tests - FrontEnd

#127 added front end info to sprint2 md
  Sprint2.md
Labels: olxclone, sprint2

#128 removed unecessary lines from sprint2 md
  Sprint2.md
Labels: sprint2

#129 fix unit test case of login page navigation
  workspaces/client/cypress/integration/unit/login.spec.js
  workspaces/client/cypress/integration/unit/signup.spec.js
Labels: sprint2, unit tests - FrontEnd

#146 Go env test bug fix
  workspaces/server/utilities/dbUtilities.go
  workspaces/server/utilities/mailUtility.go
Labels: bug, testing, sprint3

#148 Redux integration fixes
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/LoaderComponent/LoaderComponent.css
  workspaces/client/src/LoaderComponent/LoaderComponent.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/ReduxActions/LoginActions.ts
  workspaces/client/src/ReduxActions/SignupActions.ts
  workspaces/client/src/ReduxSlices/LoginSlice.ts
  workspaces/client/src/ReduxSlices/SignupSlice.ts
  workspaces/client/src/Store/store.ts
  workspaces/client/src/VerifyEmailComponent/VerifyEmailComponent.tsx
Labels: sprint3

#149 added missing deps
  workspaces/client/package.json
  yarn.lock
Labels: sprint3

#150 added fetch user details api
  workspaces/server/controller.go
  workspaces/server/handlers/getUserDetails.go
  workspaces/server/paths/paths.go
Labels: api, sprint3, backend

#152 Integration profile update
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/NavBarComponent/NavBarComponent.tsx
  workspaces/client/src/ProfileComponent/ProfileComponent.tsx
  workspaces/client/src/ReduxActions/UserProfileActions.ts
  workspaces/client/src/ReduxSlices/UserProfileSlice.ts
  workspaces/client/src/Store/store.ts
  workspaces/client/src/Types/user.ts
  workspaces/client/src/app.constants.ts
  workspaces/server/controller.go
  workspaces/server/handlers/getUserDetails.go
Labels: api, sprint3, backend, frontend

#154 Integrate products api
  workspaces/client/src/CardComponent/CardComponent.tsx
  workspaces/client/src/HomePageComponent/HomePageComponent.tsx
  workspaces/client/src/ProfileComponent/ProfileComponent.tsx
  workspaces/client/src/ReduxActions/ProductActions.ts
  workspaces/client/src/ReduxActions/UserProfileActions.ts
  workspaces/client/src/ReduxSlices/ProductSlice.ts
  workspaces/client/src/Store/store.ts
  workspaces/client/src/Types/user.ts
  workspaces/client/src/app.constants.ts
  workspaces/server/handlers/getProductsHandler.go
Labels: api, sprint3, backend, frontend

#155 Front end tests
  workspaces/client/src/CardComponent/CardComponent.tsx
Labels: ui, sprint3
