Repository OLXClone-SE/OLXClone, pull requests merged in 2022-02, with the labels that each got.

#44 ForgotPassword implementation, routing
  workspaces/client/src/ForgotPasswordComponent/ForgotPasswordComponent.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/index.tsx
Labels: sprint1, ui

#43 OLXCLONE-41:add signup api with otp verification
  workspaces/server/constants/dbconstants.go
  workspaces/server/controller.go
  workspaces/server/go.mod
  workspaces/server/handlers/forgotPasswordHandler.go
  workspaces/server/handlers/loginHandler.go
  workspaces/server/handlers/signupHandler.go
  workspaces/server/handlers/userVerificationHandler.go
  workspaces/server/models/usermodels.go
  workspaces/server/package.json
  workspaces/server/paths/paths.go
  workspaces/server/utilities/otpUtilities.go
Labels: sprint1, api

#45 Olx signup
  workspaces/client/package.json
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/OTPComponent/OTPComponent.tsx
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/index.tsx
  yarn.lock
Labels: olxclone, sprint1, ui

#47 OLXCLONE-46: refactor forgot password handler to make use of common e…
  workspaces/server/constants/dbconstants.go
  workspaces/server/controller.go
  workspaces/server/handlers/forgotPasswordHandler.go
  workspaces/server/handlers/resetPasswordHandler.go
  workspaces/server/handlers/userVerificationHandler.go
  workspaces/server/paths/paths.go
Labels: sprint1, api

#48 fixed reset password otp bug
  workspaces/server/utilities/otpUtilities.go
Labels: sprint1

#51 Added reset password functionality
  workspaces/client/src/OTPComponent/OTPComponent.tsx
  workspaces/client/src/ResetComponent/ResetPasswordComponent.tsx
  workspaces/client/src/index.tsx
Labels: olxclone, sprint1, ui

#52 added_sprint1_md_file
  Sprint1.md
Labels: sprint1

#57 OTP functionality implementation
  workspaces/client/src/ForgotPasswordComponent/ForgotPasswordComponent.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
Labels: sprint1, ui

#58 Mocking user login
  workspaces/client/src/LoginComponent/LoginComponent.tsx
Labels: olxclone, sprint1, ui

#56 OLXCLONE-54: add signup api details to sprint1.md file
  Sprint1.md
Labels: documentation, sprint1, api

#59 Routing to login after successfull signup
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
Labels: olxclone, sprint1, ui

#60 Signup component Updates
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
Labels: sprint1, ui

#61 fixed
  workspaces/server/handlers/userVerificationHandler.go
Labels: sprint1

#63 fixed otp relate bug
  workspaces/server/handlers/userVerificationHandler.go
Labels: bug, sprint1, api

#65 edit sprint1.md file
  Sprint1.md
Labels: documentation, sprint1, api

#66 fix signup api
  workspaces/server/handlers/signupHandler.go
Labels: sprint1, api

#68 Header Changes
  workspaces/client/public/Favicon.ico
  workspaces/client/public/index.html
  workspaces/client/public/manifest.json
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
Labels: ui

#69 Singup component clean up
  workspaces/client/src/ErrorMessages.tsx
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/ValidationRegex.tsx
Labels: olxclone, ui

#71 add github username map to README file
  README.md
Labels: documentation

#72 added redux dependencies
  workspaces/client/package-lock.json
  workspaces/client/package.json
  yarn.lock
Labels: sprint2

#74 added thunk dependencies
  workspaces/client/package.json
  yarn.lock
Labels: sprint2

#76 Setting up redux
  workspaces/client/package.json
  workspaces/client/src/CounterComponent/CounterComponent.tsx
  workspaces/client/src/ReduxSlices/CounterSlice.ts
  workspaces/client/src/Store/hooks.ts
  workspaces/client/src/Store/store.ts
  workspaces/client/src/index.tsx
  yarn.lock
Labels: sprint2

#79 Fixed signup redirection issue
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/Utils/ErrorMessages.ts
  workspaces/client/src/Utils/ValidationRegex.ts
Labels: bug, sprint2

#80 Sanitizing signup
  workspaces/client/src/CopyrightComponent/CopyrightComponent.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/Types/SignUpComponentTypes.ts
  workspaces/client/src/Utils/validators.ts
Labels: sprint2

#82 Verify Email implementation
  workspaces/client/src/VerifyEmailComponent/VerifyEmailComponent.tsx
  workspaces/client/src/index.tsx
Labels: ui, sprint2

#84 Sanitized login page
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/Types/LoginComponentTypes.ts
Labels: bug, sprint2

#86 Setting up Signup api connections
  workspaces/client/src/ReduxActions/SignupActions.ts
  workspaces/client/src/ReduxActions/VerifyUserActions.ts
  workspaces/client/src/ReduxSlices/CounterSlice.ts
  workspaces/client/src/ReduxSlices/SignupSlice.ts
  workspaces/client/src/ReduxSlices/VerifyUserSlice.ts
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/Store/store.ts
  workspaces/client/src/Types/SignUpComponentTypes.ts
  workspaces/client/src/Types/user.ts
  workspaces/client/src/VerifyEmailComponent/VerifyEmailComponent.tsx
  workspaces/client/src/app.constants.ts
  workspaces/client/src/axiosInstance.ts
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/main.go
Labels: api, sprint2
