Repository OLXClone-SE/OLXClone, pull requests merged in 2022-01, with the labels that each got.

#1 updated read me file
  README.md
Labels: olxclone

#5 updated readme
  README.md
Labels: olxclone

#10 OLXClone#9: setup yarn workspaces to maintain as a mono repo
  package.json
Labels: project-setup

#12 OLXClone#11: add workspaces for client and server applications using …
  workspaces/client/README.md
  workspaces/server/README.md
Labels: project-setup

#13 added client setup
  .gitignore
  package-lock.json
  package.json
  workspaces/client/.gitignore
  workspaces/client/README.md
  workspaces/client/README.old.md
  workspaces/client/package.json
  workspaces/client/public/favicon.ico
  workspaces/client/public/index.html
  workspaces/client/public/logo192.png
  workspaces/client/public/logo512.png
  workspaces/client/public/manifest.json
  workspaces/client/public/robots.txt
  workspaces/client/src/App.css
  workspaces/client/src/App.test.tsx
  workspaces/client/src/App.tsx
  workspaces/client/src/index.css
  workspaces/client/src/index.tsx
  workspaces/client/src/logo.svg
  workspaces/client/src/react-app-env.d.ts
  workspaces/client/src/reportWebVitals.ts
  workspaces/client/src/setupTests.ts
  workspaces/client/tsconfig.json
  workspaces/client/yarn.lock
  yarn.lock
Labels: project-setup

#15 Cleaning Boiler Plate Code
  workspaces/client/README.md
  workspaces/client/README.old.md
  workspaces/client/public/favicon.ico
  workspaces/client/public/logo192.png
  workspaces/client/public/logo512.png
  workspaces/client/public/robots.txt
  workspaces/client/src/App.css
  workspaces/client/src/App.test.tsx
  workspaces/client/src/App.tsx
  workspaces/client/src/index.tsx
  workspaces/client/src/logo.svg
  workspaces/client/src/reportWebVitals.ts
Labels: project-setup

#18 hot reload added
  .gitignore
  package.json
  workspaces/server/.air.toml
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/main.go
  workspaces/server/package.json
Labels: project-setup

#20 Login api
  .gitignore
  workspaces/server/.air.toml
  workspaces/server/constants/dbconstants.go
  workspaces/server/controller.go
  workspaces/server/go.mod
  workspaces/server/go.sum
  workspaces/server/handlers/loginHandler.go
  workspaces/server/main.go
  workspaces/server/models/usermodels.go
  workspaces/server/paths/paths.go
  workspaces/server/utilities/dbUtilities.go
  workspaces/server/utilities/jsonUtilities.go
  workspaces/server/utilities/responseWriterUtilities.go
Labels: sprint1

#27 login page created, rote added
  workspaces/client/package.json
  workspaces/client/src/App.tsx
  workspaces/client/src/LoginComponent/LoginComponent.tsx
  workspaces/client/src/index.tsx
  yarn.lock
Labels: sprint1

#28 Added signup page
  workspaces/client/src/SignUpComponent/SignUpComponent.tsx
  workspaces/client/src/index.tsx
Labels: olxclone, sprint1
